"""
Django settings for Tradcutor_TEA project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from typing import Mapping

from django.core.exceptions import ImproperlyConfigured
from dotenv import dotenv_values


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y=j0#1e20l)f(%69arj=(zw*ivg70#ni*jn!bghmgh4rpcd=n='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# The applications were registered using the full path to their `AppConfig` classes to make the configuration 
# loaded by Django explicit and avoid relying solely on automatic detection. Furthermore, this ensures that 
# if additional classes are added to `apps.py` in the future, they will not be loaded automatically; instead, 
# you will be able to choose which one to use.

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'backend.accounts.apps.AccountsConfig',
    'backend.preferences.apps.PreferencesConfig',
    'backend.interpretation.apps.InterpretationConfig',
    'backend.audit.apps.AuditConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Tradcutor_TEA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Tradcutor_TEA.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Define separate credential profiles for runtime and migration operations.
# This enables least-privilege access and supports distinct credentials for
# migrations versus normal app usage.
DATABASE_PROFILES = {
    "app": {
        "credentials_file": BASE_DIR / ".secrets" / "db-app.env",
        "expected_user": "traductor_tea_app",
    },
    "migrate": {
        "credentials_file": BASE_DIR / ".secrets" / "db-migrate.env",
        "expected_user": "traductor_tea_migrator",
    },
    "test": {
        "credentials_file": BASE_DIR / ".secrets" / "db-test.env",
        "expected_user": "traductor_tea_test",
    }
}

# Select the active database profile from the environment.
DATABASE_PROFILE = os.environ.get(
    "DJANGO_DB_PROFILE",
    "app",
).strip().lower()

if DATABASE_PROFILE not in DATABASE_PROFILES:
    allowed_profiles = ", ".join(sorted(DATABASE_PROFILES))

    raise ImproperlyConfigured(
        f"Invalid DJANGO_DB_PROFILE: {DATABASE_PROFILE!r}. "
        f"Allowed values: {allowed_profiles}."
    )


def read_dotenv_file(path: Path) -> dict[str, str]:
    """Read a dotenv file without modifying os.environ.

    Missing files are allowed because production deployments may inject
    all settings directly through environment variables.
    
    Args:
        path: Path to the dotenv file to read.
    
    Returns:
        A dictionary of key-value pairs from the dotenv file. Returns an empty
        dict if the file does not exist.
    """
    if not path.is_file():
        return {}

    return {
        key: value
        for key, value in dotenv_values(
            path,
            encoding="utf-8",
            interpolate=False).items()
        if value is not None
    }

# Load common settings first, then profile-specific credentials.
common_config = read_dotenv_file(BASE_DIR / ".env")

profile_config = read_dotenv_file(
    DATABASE_PROFILES[DATABASE_PROFILE]["credentials_file"]
)

# Database configuration precedence:
# 1. Real operating-system environment variables.
# 2. Selected profile dotenv credentials.
# 3. Common local configuration file.
database_config: Mapping[str, str] = {
    **common_config,
    **profile_config,
    **os.environ,
}


def get_required_setting(name: str) -> str:
    """Obtain a required database configuration value.
    
    Args:
        name: The name of the configuration setting to retrieve.
    
    Returns:
        The string value of the configuration setting.
    
    Raises:
        ImproperlyConfigured: If the setting is missing or empty.
    """
    value = database_config.get(name)

    if value is None or not str(value).strip():
        raise ImproperlyConfigured(
            f"Missing required database setting: {name}"
        )

    return str(value).strip()


def get_integer_setting(
    name: str,
    *,
    default: int,
    minimum: int = 0,
    maximum: int | None = None,
) -> int:
    """Parse and validate an integer database configuration value.
    
    Args:
        name: The name of the configuration setting to retrieve.
        default: The default value to use if the setting is not found.
        minimum: The minimum allowed value (inclusive). Defaults to 0.
        maximum: The maximum allowed value (inclusive). Defaults to None (no limit).
    
    Returns:
        The parsed integer value after validation.
    
    Raises:
        ImproperlyConfigured: If the value cannot be parsed as an integer, or if
            it falls outside the minimum/maximum range.
    """
    raw_value = database_config.get(name, str(default))

    try:
        value = int(raw_value)
    except (TypeError, ValueError) as exc:
        raise ImproperlyConfigured(
            f"Database setting {name} must be an integer."
        ) from exc

    if value < minimum:
        raise ImproperlyConfigured(
            f"Database setting {name} must be at least {minimum}."
        )

    if maximum is not None and value > maximum:
        raise ImproperlyConfigured(
            f"Database setting {name} must not exceed {maximum}."
        )

    return value

# Enforce that the selected profile uses the expected database user.
database_user = get_required_setting("POSTGRES_USER")
expected_database_user = DATABASE_PROFILES[DATABASE_PROFILE]["expected_user"]

if database_user != expected_database_user:
    raise ImproperlyConfigured(
        f"Database profile {DATABASE_PROFILE!r} must use "
        f"{expected_database_user!r}, not {database_user!r}."
    )

# Parse common database connection parameters with safe defaults.
database_port = get_integer_setting(
    "POSTGRES_PORT",
    default=5432,
    minimum=1,
    maximum=65535,
)

connection_max_age = get_integer_setting(
    "POSTGRES_CONN_MAX_AGE",
    default=60,
    minimum=0,
)

connection_timeout = get_integer_setting(
    "POSTGRES_CONNECT_TIMEOUT",
    default=5,
    minimum=1,
    maximum=60,
)

# Allowed PostgreSQL SSL modes for the connection.
allowed_ssl_modes = {
    "disable",
    "allow",
    "prefer",
    "require",
    "verify-ca",
    "verify-full",
}

ssl_mode = database_config.get(
    "POSTGRES_SSLMODE",
    "prefer",
).strip().lower()

if ssl_mode not in allowed_ssl_modes:
    raise ImproperlyConfigured(
        "Invalid POSTGRES_SSLMODE. Allowed values: "
        + ", ".join(sorted(allowed_ssl_modes))
    )

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": get_required_setting("POSTGRES_DB"),
        "USER": database_user,
        "PASSWORD": get_required_setting("POSTGRES_PASSWORD"),
        "HOST": get_required_setting("POSTGRES_HOST"),
        "PORT": str(database_port),
        "CONN_MAX_AGE": connection_max_age,
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {
            "sslmode": ssl_mode,
            "connect_timeout": connection_timeout,
        },
        "TEST": {
            "NAME": "test_traductor_tea_db",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Customized user

AUTH_USER_MODEL = 'accounts.CustomUser'