# Generated by Django 6.0.6 on 2026-07-25 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMRateLimitState',
            fields=[
                ('subject_hash', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_llm_quota_subject', message='El identificador de cuota debe contener exactamente 64 caracteres hexadecimales en minúsculas.', regex='\\A[0-9a-f]{64}\\Z')])),
                ('minute_started_at', models.DateTimeField()),
                ('minute_requests', models.PositiveIntegerField(default=0)),
                ('minute_tokens', models.PositiveIntegerField(default=0)),
                ('day_started_at', models.DateTimeField()),
                ('day_requests', models.PositiveIntegerField(default=0)),
                ('day_tokens', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'default_permissions': (),
                'indexes': [models.Index(fields=['updated_at'], name='interpret_quota_updated_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('subject_hash__regex', '^[0-9a-f]{64}$')), name='interpret_quota_subject_hash_format')],
            },
        ),
    ]
