"""Django system checks for LLM cache and quota configuration invariants."""

from __future__ import annotations

from collections.abc import Iterable
from itertools import product

from django.apps import AppConfig
from django.conf import settings
from django.core.checks import Error, Tags, register
from django.core.exceptions import ImproperlyConfigured

from backend.preferences.models import InterpretationDetail, UserPreferences

from .input_validation import ContextSpeakerRelation
from .prompts import build_messages
from .provider import estimate_request_tokens
from .transient_cache import get_llm_transient_cache


# Record the transaction as a check belonging to the caches category.
@register(Tags.caches)
def check_llm_transient_cache(
    app_configs: Iterable[AppConfig] | None,
    **kwargs: object,
) -> list[Error]:
    """Verify that the configured transient LLM cache satisfies its policy.

    Args:
        app_configs: Optional application subset selected by Django checks.
        **kwargs: Additional arguments supplied by Django's check framework.

    Returns:
        An empty list when valid, or a closed configuration error.
    """
    try:
        get_llm_transient_cache()
    except ImproperlyConfigured as exc:
        return [
            Error(
                # Capture the exact descriptive text returned by the get_llm_transient_cache() function.
                str(exc),
                # Explain the specific action that must be taken to fix the configuration.
                hint=(
                    "Configura LLM_DUPLICATE_CACHE_ALIAS y, cuando se exija, "
                    "utiliza una caché compartida entre procesos."
                ),
                # Unique error identifier.
                id="interpretation.E001",
            )
        ]

    return []


def _maximum_accepted_token_reservation() -> int:
    """Calculate the largest estimate generated by accepted request settings.

    Returns:
        Maximum token reservation across every closed prompt preference.
    """
    # Each double quote is escaped as \" in JSON, thereby generating the
    # longest possible serialization among accepted ordinary characters.
    # It is used solely to estimate the worst-case token count, without actual text.
    # Keep up to both optional contexts non-empty while reserving one
    # character for the required target message.
    context_count = min(2, settings.LLM_MAX_INPUT_CHARACTERS - 1)
    maximum_length_message = '"' * (
        settings.LLM_MAX_INPUT_CHARACTERS - context_count
    )
    # Add one escapable character to each included context for worst-case
    # JSON size estimation.
    previous_context = '"' if context_count >= 1 else ""
    following_context = '"' if context_count == 2 else ""
    reservations: list[int] = []

    # show_content_warnings is not included because it does not modify the request
    # sent to Groq nor, consequently, its token estimate.
    for detail, visual_support, offensive_language in product(
        InterpretationDetail.values,
        (False, True),
        (False, True),
    ):
        preferences = UserPreferences(
            interpretation_detail=detail,
            visual_support_enabled=visual_support,
            show_offensive_language=offensive_language,
        )
        reservations.append(
            estimate_request_tokens(
                messages=build_messages(
                    # The three fields share one total limit, so assigning all
                    # characters to escapable values remains the worst case.
                    target_message=maximum_length_message,
                    previous_context=previous_context,
                    previous_context_speaker=(
                        ContextSpeakerRelation.DIFFERENT_FROM_TARGET_AUTHOR
                        if previous_context
                        else ContextSpeakerRelation.UNKNOWN
                    ),
                    following_context=following_context,
                    following_context_speaker=(
                        ContextSpeakerRelation.DIFFERENT_FROM_TARGET_AUTHOR
                        if following_context
                        else ContextSpeakerRelation.UNKNOWN
                    ),
                    preferences=preferences,
                ),
                max_completion_tokens=settings.LLM_MAX_COMPLETION_TOKENS,
            )
        )

    return max(reservations)


# Used for checks focused on the compatibility of configurations, dependencies, or versions.
@register(Tags.compatibility)
def check_llm_request_fits_empty_quotas(
    app_configs: Iterable[AppConfig] | None,
    **kwargs: object,
) -> list[Error]:
    """Ensure every request accepted by validation can fit an empty window.

    Args:
        app_configs: Optional application subset selected by Django checks.
        **kwargs: Additional arguments supplied by Django's check framework.

    Returns:
        Configuration errors for token quotas below the maximum reservation.
    """
    maximum_reservation = _maximum_accepted_token_reservation()
    quota_settings = {
        "LLM_USER_TOKENS_PER_MINUTE": settings.LLM_USER_TOKENS_PER_MINUTE,
        "LLM_USER_TOKENS_PER_DAY": settings.LLM_USER_TOKENS_PER_DAY,
        "LLM_GLOBAL_TOKENS_PER_MINUTE": settings.LLM_GLOBAL_TOKENS_PER_MINUTE,
        "LLM_GLOBAL_TOKENS_PER_DAY": settings.LLM_GLOBAL_TOKENS_PER_DAY,
    }

    return [
        Error(
            (
                f"{setting_name} no admite la mayor reserva posible "
                f"({maximum_reservation} unidades estimadas)."
            ),
            hint=(
                "Reduce los límites de entrada/salida o aumenta la cuota "
                "local sin superar los límites reales de Groq."
            ),
            id="interpretation.E002",
        )
        for setting_name, configured_limit in quota_settings.items()
        if configured_limit < maximum_reservation
    ]
