# Generated by Django 6.0.6 on 2026-06-28 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_support_enabled', models.BooleanField(default=True)),
                ('show_offensive_language', models.BooleanField(default=False)),
                ('show_content_warnings', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('system', 'Usar el tema del sistema')], default='system', max_length=16)),
                ('interpretation_detail', models.CharField(choices=[('brief', 'Corta y directa'), ('standard', 'Estándar'), ('detailed', 'Detallada')], default='standard', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('theme__in', ['light', 'dark', 'system'])), name='preferences_theme_valid'), models.CheckConstraint(condition=models.Q(('interpretation_detail__in', ['brief', 'standard', 'detailed'])), name='preferences_interpretation_detail_valid')],
            },
        ),
    ]
