# Generated by Django 6.0.6 on 2026-06-28 21:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('account_created', 'Cuenta creada'), ('account_updated', 'Estado de seguridad de la cuenta actualizado'), ('login_succeeded', 'Inicio de sesión exitoso'), ('login_failed', 'Inicio de sesión fallido'), ('identity_rejected', 'Identidad OIDC rechazada'), ('logout', 'Cierre de sesión'), ('session_revoked', 'Sesión revocada'), ('authorization_denied', 'Autorización denegada'), ('rate_limited', 'Solicitud limitada por tasa'), ('preferences_updated', 'Preferencias actualizadas'), ('llm_request_rejected', 'Solicitud al LLM rechazada'), ('llm_provider_error', 'Error del proveedor LLM'), ('arasaac_provider_error', 'Error de ARASAAC')], max_length=32)),
                ('actor_id_snapshot', models.UUIDField(blank=True, editable=False, help_text='Copia del UUID local del actor para conservar trazabilidad si la cuenta se elimina.', null=True)),
                ('source_ip_hash', models.CharField(blank=True, help_text='Resumen HMAC-SHA-256 de la IP de origen; nunca una dirección IP sin procesar.', max_length=64, validators=[django.core.validators.RegexValidator(code='invalid_source_hash', message='El hash de origen debe ser un resumen hexadecimal SHA-256 en minúsculas.', regex='\\A[0-9a-f]{64}\\Z')])),
                ('request_id', models.UUIDField(blank=True, help_text='Identificador de correlación opcional generado por la aplicación.', null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de seguridad',
                'verbose_name_plural': 'eventos de seguridad',
                'ordering': ('-occurred_at',),
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['event_type', '-occurred_at'], name='audit_event_type_time_idx'), models.Index(fields=['actor', '-occurred_at'], name='audit_actor_time_idx'), models.Index(condition=models.Q(('actor_id_snapshot__isnull', False)), fields=['actor_id_snapshot', '-occurred_at'], name='audit_actor_snapshot_time_idx'), models.Index(condition=models.Q(('request_id__isnull', False)), fields=['request_id'], name='audit_request_id_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('event_type__in', ['account_created', 'account_updated', 'login_succeeded', 'login_failed', 'identity_rejected', 'logout', 'session_revoked', 'authorization_denied', 'rate_limited', 'preferences_updated', 'llm_request_rejected', 'llm_provider_error', 'arasaac_provider_error'])), name='audit_event_type_valid')],
            },
        ),
    ]
