# Generated by Django 6.0.6 on 2026-08-03 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='securityevent',
            name='audit_event_type_valid',
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('account_created', 'Cuenta creada'), ('account_updated', 'Estado de seguridad de la cuenta actualizado'), ('login_succeeded', 'Inicio de sesión exitoso'), ('login_failed', 'Inicio de sesión fallido'), ('identity_rejected', 'Identidad OIDC rechazada'), ('logout', 'Cierre de sesión'), ('session_revoked', 'Sesión revocada'), ('authorization_denied', 'Autorización denegada'), ('rate_limited', 'Solicitud limitada por tasa'), ('preferences_updated', 'Preferencias actualizadas'), ('llm_output_rejected', 'Salida del LLM rechazada'), ('arasaac_provider_error', 'Error de ARASAAC')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='securityevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['account_created', 'account_updated', 'login_succeeded', 'login_failed', 'identity_rejected', 'logout', 'session_revoked', 'authorization_denied', 'rate_limited', 'preferences_updated', 'llm_output_rejected', 'arasaac_provider_error'])), name='audit_event_type_valid'),
        ),
    ]
