# Generated by Django 6.0.8 on 2026-08-24 23:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_remove_securityevent_audit_event_type_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL, verbose_name='actor'),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='actor_id_snapshot',
            field=models.UUIDField(blank=True, editable=False, help_text='Copia del UUID local del actor para conservar trazabilidad si la cuenta se elimina.', null=True, verbose_name='copia del UUID del actor'),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('account_created', 'Cuenta creada'), ('account_updated', 'Estado de seguridad de la cuenta actualizado'), ('login_succeeded', 'Inicio de sesión exitoso'), ('login_failed', 'Inicio de sesión fallido'), ('identity_rejected', 'Identidad OIDC rechazada'), ('logout', 'Cierre de sesión'), ('session_revoked', 'Sesión revocada'), ('authorization_denied', 'Autorización denegada'), ('rate_limited', 'Solicitud limitada por tasa'), ('preferences_updated', 'Preferencias actualizadas'), ('llm_output_rejected', 'Salida del LLM rechazada'), ('arasaac_provider_error', 'Error de ARASAAC')], max_length=32, verbose_name='tipo de evento'),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='occurred_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora del evento'),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='request_id',
            field=models.UUIDField(blank=True, help_text='Identificador de correlación opcional generado por la aplicación.', null=True, verbose_name='identificador de solicitud'),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='source_ip_hash',
            field=models.CharField(blank=True, help_text='Resumen HMAC-SHA-256 de la IP de origen; nunca una dirección IP sin procesar.', max_length=64, validators=[django.core.validators.RegexValidator(code='invalid_source_hash', message='El hash de origen debe contener 64 caracteres hexadecimales SHA-256 en minúsculas.', regex='\\A[0-9a-f]{64}\\Z')], verbose_name='resumen de la IP de origen'),
        ),
    ]
