"""
Django settings for Traductor_TEA project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import secrets
from collections.abc import Mapping
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import dotenv_values


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Limit secret files to a small, predictable size before decoding them.
MAX_SECRET_FILE_BYTES = 4096


def get_database_credentials_file(
    profile_name: str,
    default_filename: str,
) -> Path:
    """Resolve the dotenv file that stores credentials for a database profile.

    Args:
        profile_name: The profile name used to build the override environment
        variable name ("app", "migrate", "test").
        default_filename: The local development filename under `.secrets`.

    Returns:
        The configured credentials file path, preferring an explicit environment
        override such as `DJANGO_DB_APP_CREDENTIALS_FILE`.
    """
    override_name = f"DJANGO_DB_{profile_name.upper()}_CREDENTIALS_FILE"
    override_value = os.environ.get(override_name, "").strip()

    if override_value: # For an alternative path, ensure it is absolute to avoid ambiguity.
        override_path = Path(override_value)

        if not override_path.is_absolute():
            raise ImproperlyConfigured(
                f"{override_name} debe ser una ruta absoluta."
            )

        # For Docekr (/run/secrets/...)
        return override_path

    # For local development (~.secrets/...)
    return BASE_DIR / ".secrets" / default_filename


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECRET_KEY is loaded from backend-only configuration after the common and
# profile-specific settings have been resolved below.

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Accept only the browser hostname and the loopback address used by the
# container healthcheck in the local HTTPS development environment.
ALLOWED_HOSTS = [
    "localhost", 
    "127.0.0.1",
    ]


# Emit only minimized interpretation metadata to the container standard output.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "llm_operational": {
            # Include only severity, logger name, and the pre-sanitized event.
            "format": "{levelname} {name} {message}",
            # str format style.
            "style": "{",
        },
    },
    "handlers": {
        "llm_console": {
            "class": "logging.StreamHandler",
            "formatter": "llm_operational",
            "level": "INFO",
            "stream": "ext://sys.stdout",
        },
    },
    "loggers": {
        "backend.interpretation.provider": {
            "handlers": ["llm_console"],
            "level": "INFO",
            "propagate": False,
        },
        "backend.interpretation.arasaac": {
            "handlers": ["llm_console"],
            "level": "INFO",
            "propagate": False,
        },
        "backend.interpretation.services": {
            "handlers": ["llm_console"],
            "level": "INFO",
            "propagate": False,
        },
        "backend.interpretation.throttles": {
            "handlers": ["llm_console"],
            "level": "INFO",
            "propagate": False,
        },
        "backend.interpretation.rate_limit_audit": {
            "handlers": ["llm_console"],
            "level": "INFO",
            "propagate": False,
        },
        "backend.audit.services": {
            "handlers": ["llm_console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# Application definition

# The applications were registered using the full path to their `AppConfig` classes to make the configuration 
# loaded by Django explicit and avoid relying solely on automatic detection. Furthermore, this ensures that 
# if additional classes are added to `apps.py` in the future, they will not be loaded automatically; instead, 
# you will be able to choose which one to use.

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'backend.accounts.apps.AccountsConfig',
    'backend.preferences.apps.PreferencesConfig',
    'backend.interpretation.apps.InterpretationConfig',
    'backend.audit.apps.AuditConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'backend.audit.middleware.RequestIdMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Traductor_TEA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Traductor_TEA.wsgi.application'


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication", # Use session-based authentication for web clients.
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated", # Only authenticated users can access to the endpoints.
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer", # Force that all responses are in JSON format.
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser", # Only accepts JSON requests to the API endpoints.
    ],
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Define separate credential profiles for runtime and migration operations.
# This enables least-privilege access and supports distinct credentials for
# migrations versus normal app usage.
DATABASE_PROFILES = {
    "app": {
        "credentials_file": get_database_credentials_file(
            "app",
            "db-app.env",
        ),
        "expected_user": "traductor_tea_app",
    },
    "migrate": {
        "credentials_file": get_database_credentials_file(
            "migrate",
            "db-migrate.env",
        ),
        "expected_user": "traductor_tea_migrator",
    },
    "test": {
        "credentials_file": get_database_credentials_file(
            "test",
            "db-test.env",
        ),
        "expected_user": "traductor_tea_test",
    }
}

# Select the active database profile from the environment.
DATABASE_PROFILE = os.environ.get(
    "DJANGO_DB_PROFILE",
    "app",
).strip().lower()

if DATABASE_PROFILE not in DATABASE_PROFILES:
    allowed_profiles = ", ".join(sorted(DATABASE_PROFILES))

    raise ImproperlyConfigured(
        f"DJANGO_DB_PROFILE no válido: {DATABASE_PROFILE!r}. "
        f"Valores permitidos: {allowed_profiles}."
    )


def read_dotenv_file(path: Path) -> dict[str, str]:
    """Read a dotenv file without modifying os.environ.

    Missing files are allowed because production deployments may inject
    all settings directly through environment variables.
    
    Args:
        path: Path to the dotenv file to read.
    
    Returns:
        A dictionary of key-value pairs from the dotenv file. Returns an empty
        dict if the file does not exist.
    """
    if not path.is_file():
        return {}

    return {
        key: value
        for key, value in dotenv_values(
            path,
            encoding="utf-8",
            interpolate=False).items()
        if value is not None
    }

# Load common settings first, then profile-specific credentials.
common_config = read_dotenv_file(BASE_DIR / ".env")

profile_config = read_dotenv_file(
    DATABASE_PROFILES[DATABASE_PROFILE]["credentials_file"]
)

aplication_config: Mapping[str, str] = { # Mapping of str key to str value.
    **common_config, # Firstly inserts the common settings from .env file
    **profile_config, # Secondly inserts the profile specific settings (app, migrate or test). If the same key exists in both,
                      # the profile-specific value will override the common one.
    **os.environ, # Finally inserts the environment variables of the operating system or the container. It has the highest priority.
}


def get_secret_setting(
    name: str,
    file_name: str,
    *,
    default_file: Path | None = None,
) -> str:
    """Load an optional secret from direct configuration or an absolute file
    (GOOGLE_OIDC_CLIENT_SECRET=secret-value or
    GOOGLE_OIDC_CLIENT_SECRET_FILE=/run/secrets/google_oidc_client_secret).

    Args:
        name: The direct configuration key used outside containerized runtime.
        file_name: The configuration key containing an absolute secret file path.
        default_file: Optional local secret file used only when neither explicit
            source is configured.

    Raises:
        ImproperlyConfigured: If both sources are configured, the file path is
        unsafe, or the secret file cannot be read and validated.

    Returns:
        The normalized secret value, or an empty string when neither source is
        configured.
    """
    direct_value = str(aplication_config.get(name, "") or "").strip()
    configured_file = str(aplication_config.get(file_name, "") or "").strip()

    if direct_value and configured_file:
        raise ImproperlyConfigured(
            f"Solo debe configurarse uno de estos valores: {name} o {file_name}."
        )

    if direct_value:
        if (
            len(direct_value.encode("utf-8")) > MAX_SECRET_FILE_BYTES
            or "\x00" in direct_value
            or "\n" in direct_value
            or "\r" in direct_value
        ):
            raise ImproperlyConfigured(
                f"El secreto configurado mediante {name} debe constar de una "
                "única línea válida."
            )

        return direct_value

    # If neither explicit source exists, use the optional local-only default.
    if not configured_file:
        if default_file is None:
            return ""

        if not default_file.is_absolute():
            raise ImproperlyConfigured(
                "La ruta predeterminada del secreto debe ser absoluta."
            )

        if not default_file.is_file():
            return ""

        secret_path = default_file
    else:
        secret_path = Path(configured_file)

    if configured_file and not secret_path.is_absolute():
        raise ImproperlyConfigured(f"{file_name} debe ser una ruta absoluta.")

    try:
        # Open in binary mode for the bytes control.
        with secret_path.open("rb") as secret_file:
            # 4096+1 bytes are read, so that if the file is very large, loading 
            # it into memory is avoided and thus, you can know if the size falls within the limit.
            raw_secret = secret_file.read(MAX_SECRET_FILE_BYTES + 1)
    except OSError as exc:
        raise ImproperlyConfigured(
            f"No se pudo leer el secreto configurado mediante {file_name}."
        ) from exc

    if len(raw_secret) > MAX_SECRET_FILE_BYTES:
        raise ImproperlyConfigured(
            f"El secreto configurado mediante {file_name} es demasiado grande."
        )

    try:
        secret_value = raw_secret.decode("utf-8").strip()
    except UnicodeDecodeError as exc:
        raise ImproperlyConfigured(
            f"El secreto configurado mediante {file_name} debe estar codificado "
            "en UTF-8."
        ) from exc

    if (
        not secret_value
        or "\x00" in secret_value
        or "\n" in secret_value
        or "\r" in secret_value
    ):
        raise ImproperlyConfigured(
            f"El secreto configurado mediante {file_name} debe constar de una "
            "única línea no vacía."
        )

    return secret_value


EPHEMERAL_SECRET_KEY_PROFILES = frozenset({"migrate", "test"})


def get_django_secret_key(
    *,
    local_secret_file: Path | None = None,
) -> str:
    """Load the runtime Django signing key or create an offline-only key.

    The HTTP application must receive a stable external secret. Migration and
    test processes instead receive an independent ephemeral key so the runtime
    secret is not distributed to tasks that do not serve authenticated traffic.

    Args:
        local_secret_file: Optional local file override used by focused tests.

    Raises:
        ImproperlyConfigured: If the application profile has no configured key,
            or if a configured key does not meet Django's strength guidance.

    Returns:
        A strong key suitable for Django cryptographic signing in this process.
    """
    default_file = local_secret_file or (
        BASE_DIR / ".secrets" / "django-secret-key.txt"
    )
    secret_key = get_secret_setting(
        "DJANGO_SECRET_KEY",
        "DJANGO_SECRET_KEY_FILE",
        default_file=default_file,
    )

    if not secret_key and DATABASE_PROFILE in EPHEMERAL_SECRET_KEY_PROFILES:
        # Offline tasks do not need signatures to remain valid after exit.
        secret_key = secrets.token_urlsafe(64)

    if not secret_key:
        raise ImproperlyConfigured(
            "Debe configurarse DJANGO_SECRET_KEY o DJANGO_SECRET_KEY_FILE "
            "para el perfil de ejecución de la aplicación."
        )

    if (
        len(secret_key) < 50
        or len(set(secret_key)) < 5
        or secret_key.startswith("django-insecure-")
    ):
        raise ImproperlyConfigured(
            "La clave secreta de Django debe tener al menos 50 caracteres, "
            "contener al menos 5 caracteres distintos y no usar el prefijo "
            "django-insecure-."
        )

    return secret_key


# Django uses this value for session integrity, password reset tokens, messages,
# and every signing operation that does not provide a separate key.
SECRET_KEY = get_django_secret_key()


def get_required_setting(name: str) -> str:
    """Obtain a required database configuration value.
    
    Args:
        name: The name of the configuration setting to retrieve.
    
    Returns:
        The string value of the configuration setting.
    
    Raises:
        ImproperlyConfigured: If the setting is missing or empty.
    """
    value = aplication_config.get(name)

    if value is None or not str(value).strip():
        raise ImproperlyConfigured(
            f"Falta la configuración obligatoria de la base de datos: {name}"
        )

    return str(value).strip()


def get_integer_setting(
    name: str,
    *,
    default: int,
    minimum: int = 0,
    maximum: int | None = None,
) -> int:
    """Parse and validate an optional integer configuration value.
    
    Args:
        name: The name of the configuration setting to retrieve.
        default: Value used when the setting is missing or empty.
        minimum: The minimum allowed value (inclusive). Defaults to 0.
        maximum: The maximum allowed value (inclusive). Defaults to None (no limit).
    
    Returns:
        The parsed integer value after validation.
    
    Raises:
        ImproperlyConfigured: If the value cannot be parsed as an integer, or if
            it falls outside the minimum/maximum range.
    """
    raw_value = aplication_config.get(name)

    # Empty optional entries in `.env` and Docker Compose mean "use the
    # application default"; non-empty values still receive strict validation.
    if raw_value is None or not str(raw_value).strip():
        return default

    try:
        value = int(str(raw_value).strip())
    except (TypeError, ValueError) as exc:
        raise ImproperlyConfigured(
            f"El valor de configuración {name} debe ser un número entero."
        ) from exc

    if value < minimum:
        raise ImproperlyConfigured(
            f"El valor de configuración {name} debe ser al menos {minimum}."
        )

    if maximum is not None and value > maximum:
        raise ImproperlyConfigured(
            f"El valor de configuración {name} no debe superar {maximum}."
        )

    return value


def get_boolean_setting(name: str, *, default: bool) -> bool:
    """Parse a boolean configuration setting from the environment.

    Args:
        name: The name of the configuration setting to retrieve.
        default: The default value to use when the setting is not defined.

    Returns:
        The parsed boolean value.

    Raises:
        ImproperlyConfigured: If the configured value is not a recognized
            boolean literal.
    """
    raw_value = aplication_config.get(name)

    # If the setting is not defined or is empty.
    if raw_value is None or not str(raw_value).strip():
        return default

    normalized_value = str(raw_value).strip().lower()

    if normalized_value in {"1", "true", "yes", "on"}:
        return True

    if normalized_value in {"0", "false", "no", "off"}:
        return False

    # Django does not boot if a boolean setting is misconfigured.
    raise ImproperlyConfigured(
        f"El valor de configuración {name} debe ser booleano."
    )


def get_cookie_samesite_setting(name: str, *, default: str) -> str:
    """Parse and validate a SameSite cookie setting.

    Args:
        name: The name of the configuration setting to retrieve.
        default: The default SameSite value.

    Returns:
        A Django-compatible SameSite string.

    Raises:
        ImproperlyConfigured: If the configured value is not supported.
    """
    raw_value = aplication_config.get(name, default)
    value = str(raw_value).strip()
    allowed_values = {"Strict", "Lax", "None"}

    for allowed_value in allowed_values:
        if value.lower() == allowed_value.lower():
            return allowed_value

    raise ImproperlyConfigured(
        f"El valor de configuración {name} debe ser uno de estos valores: "
        + ", ".join(sorted(allowed_values))
    )

# Enforce that the selected profile uses the expected database user.
database_user = get_required_setting("POSTGRES_USER")
expected_database_user = DATABASE_PROFILES[DATABASE_PROFILE]["expected_user"]

if database_user != expected_database_user:
    raise ImproperlyConfigured(
        f"El perfil de base de datos {DATABASE_PROFILE!r} debe usar "
        f"{expected_database_user!r}, no {database_user!r}."
    )

# Trust the original HTTPS scheme only when Django runs behind the controlled
# Caddy reverse proxy defined by the local Compose stack.
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https")
    if get_boolean_setting(
        "DJANGO_TRUST_PROXY_SSL_HEADER",
        default=False,
    )
    else None
)

# Parse common database connection parameters with safe defaults.
database_port = get_integer_setting(
    "POSTGRES_PORT",
    default=5432,
    minimum=1,
    maximum=65535,
)

connection_max_age = get_integer_setting(
    "POSTGRES_CONN_MAX_AGE",
    default=60,
    minimum=0,
)

connection_timeout = get_integer_setting(
    "POSTGRES_CONNECT_TIMEOUT",
    default=5,
    minimum=1,
    maximum=60,
)

# Allowed PostgreSQL SSL modes for the connection.
allowed_ssl_modes = {
    "disable",
    "allow",
    "prefer",
    "require",
    "verify-ca",
    "verify-full",
}

ssl_mode = aplication_config.get(
    "POSTGRES_SSLMODE",
    "prefer",
).strip().lower()

if ssl_mode not in allowed_ssl_modes:
    raise ImproperlyConfigured(
        "POSTGRES_SSLMODE no válido. Valores permitidos: "
        + ", ".join(sorted(allowed_ssl_modes))
    )

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": get_required_setting("POSTGRES_DB"),
        "USER": database_user,
        "PASSWORD": get_required_setting("POSTGRES_PASSWORD"),
        "HOST": get_required_setting("POSTGRES_HOST"),
        "PORT": str(database_port),
        "CONN_MAX_AGE": connection_max_age,
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {
            "sslmode": ssl_mode,
            "connect_timeout": connection_timeout,
        },
        "TEST": {
            "NAME": "test_traductor_tea_db",
        },
    }
}

# Keep reusable public pictogram metadata isolated from security-control caches.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "default",
    },
    # LOCATION keeps this store distinct from "default"; MAX_ENTRIES caps memory use.
    "arasaac": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "arasaac-pictograms",
        "OPTIONS": {"MAX_ENTRIES": 1_000},
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Customized user

AUTH_USER_MODEL = 'accounts.CustomUser'


# Session and CSRF cookie hardening for the browser-based OAuth/OIDC flow.
SESSION_COOKIE_HTTPONLY = True # Activates the HttpOnly flag to prevent JavaScript access from the client to the session cookie.
SESSION_COOKIE_SECURE = get_boolean_setting(
    "DJANGO_SESSION_COOKIE_SECURE",
    default=not DEBUG, # In production, the session cookie must be sent only over HTTPS (DEBUG=False).
)
SESSION_COOKIE_SAMESITE = get_cookie_samesite_setting(
    "DJANGO_SESSION_COOKIE_SAMESITE",
    default="Lax",
)
# Maximum session cookie lifetime in seconds.
SESSION_COOKIE_AGE = get_integer_setting(
    "DJANGO_SESSION_COOKIE_AGE",
    default=3600,
    minimum=300,
    maximum=86400,
)
SESSION_EXPIRE_AT_BROWSER_CLOSE = get_boolean_setting(
    "DJANGO_SESSION_EXPIRE_AT_BROWSER_CLOSE",
    default=True,
)
# If True, the session will be saved to the database on every request, even if it wasn't modified.
# This is useful for implementing a rolling session expiration.
SESSION_SAVE_EVERY_REQUEST = get_boolean_setting(
    "DJANGO_SESSION_SAVE_EVERY_REQUEST",
    default=True,
)
CSRF_COOKIE_SECURE = get_boolean_setting(
    "DJANGO_CSRF_COOKIE_SECURE",
    default=not DEBUG,
)
CSRF_COOKIE_SAMESITE = get_cookie_samesite_setting(
    "DJANGO_CSRF_COOKIE_SAMESITE",
    default="Lax",
)
# Django does not boot if session cookie secure is false in production (DEBUG=False).
if not DEBUG and not SESSION_COOKIE_SECURE:
    raise ImproperlyConfigured(
        "DJANGO_SESSION_COOKIE_SECURE debe estar habilitado cuando DEBUG es False."
    )

if not DEBUG and not CSRF_COOKIE_SECURE:
    raise ImproperlyConfigured(
        "DJANGO_CSRF_COOKIE_SECURE debe estar habilitado cuando DEBUG es False."
    )

if SESSION_COOKIE_SAMESITE == "None" and not SESSION_COOKIE_SECURE:
    raise ImproperlyConfigured(
        "SESSION_COOKIE_SECURE es obligatorio cuando SESSION_COOKIE_SAMESITE "
        "es None."
    )

if CSRF_COOKIE_SAMESITE == "None" and not CSRF_COOKIE_SECURE:
    raise ImproperlyConfigured(
        "CSRF_COOKIE_SECURE es obligatorio cuando CSRF_COOKIE_SAMESITE es None."
    )

# Avoid leaking OAuth/OIDC callback query parameters through outbound referrers.
SECURE_REFERRER_POLICY = "same-origin" # The referrer (callback with code and state) will only be sent to the same origin.

# Frontend URL used after the backend has processed the browser OAuth/OIDC callback.
# It is intentionally non-sensitive and may remain empty so local development can
# return to the same origin that received the proxied callback.
FRONTEND_AUTH_RETURN_URL = aplication_config.get(
    "FRONTEND_AUTH_RETURN_URL",
    "",
).strip()


# Google OpenID Connect configuration. The sensitive values are optional at
# process start so local commands can run without real provider credentials.
GOOGLE_OIDC_CLIENT_ID = aplication_config.get(
    "GOOGLE_OIDC_CLIENT_ID",
    "",
).strip()
GOOGLE_OIDC_CLIENT_SECRET = get_secret_setting(
    "GOOGLE_OIDC_CLIENT_SECRET",
    "GOOGLE_OIDC_CLIENT_SECRET_FILE",
)
# It must match an authorized URI in the Cloud Console.
GOOGLE_OIDC_REDIRECT_URI = aplication_config.get(
    "GOOGLE_OIDC_REDIRECT_URI",
    "",
).strip()
# URL to which the backend will redirect the user to initiate the login process.
GOOGLE_OIDC_AUTHORIZATION_ENDPOINT = (
    "https://accounts.google.com/o/oauth2/v2/auth"
)
GOOGLE_OIDC_TOKEN_ENDPOINT = "https://oauth2.googleapis.com/token"
# Triggers OpenID Connect authentication to verify user identity and retrieve an ID Token.
# Guarantees the return of the sub.
GOOGLE_OIDC_SCOPES = ("openid",)
GOOGLE_OIDC_ISSUERS = (
    "https://accounts.google.com",
    "accounts.google.com",
)
# Accepted signature algorithms for ID Tokens.
GOOGLE_OIDC_ALLOWED_ALGORITHMS = ("RS256",)
# Define how long the temporary state of the OIDC flow (state, nonce, code_verifier, etc.) can persist.
GOOGLE_OIDC_AUTH_FLOW_TTL_SECONDS = get_integer_setting(
    "GOOGLE_OIDC_AUTH_FLOW_TTL_SECONDS",
    default=300,
    minimum=60,
    maximum=900,
)
# Cache alias used for temporary Google OIDC flow metadata.
# If variable does not exist, the default cache will be used; if exists, but has None, "", 0, False..., `or default` forces the default cache;
# finnally, if after .strip() the string is empty, it is forced the default cache.
GOOGLE_OIDC_FLOW_CACHE_ALIAS = (
    str(
        aplication_config.get("GOOGLE_OIDC_FLOW_CACHE_ALIAS", "default")
        or "default"
    )
    .strip()
    or "default"
)
# In production, the OIDC flow cache must be shared across workers/containers.
# It is needed because a worker could receive the callback request from Google that was initiated by a different worker (it would fail the authentication).
# In development, a local in-memory cache is sufficient.
GOOGLE_OIDC_REQUIRE_SHARED_FLOW_CACHE = get_boolean_setting(
    "GOOGLE_OIDC_REQUIRE_SHARED_FLOW_CACHE",
    default=not DEBUG,
)
# Timeout for requests to the provider.
GOOGLE_OIDC_TIMEOUT_SECONDS = get_integer_setting(
    "GOOGLE_OIDC_TIMEOUT_SECONDS",
    default=5,
    minimum=1,
    maximum=30,
)
# Defines the maximum clock skew tolerated when validating the iat to accommodate minor time differences
# between Google and the server.
GOOGLE_OIDC_MAX_IAT_SKEW_SECONDS = get_integer_setting(
    "GOOGLE_OIDC_MAX_IAT_SKEW_SECONDS",
    default=300,
    minimum=0,
    maximum=900,
)


# Groq LLM configuration. The API key is intentionally optional at process
# start so migrations and offline tests do not require provider credentials.
GROQ_API_KEY = get_secret_setting(
    "GROQ_API_KEY",
    "GROQ_API_KEY_FILE",
)
# This backend-only secret protects privacy-minimised interpretation identifiers
# independently from Django signing. Domain separation prevents correlation
# between quota, audit, duplicate-detection, throttle, and ARASAAC cache uses.
INTERPRETATION_HMAC_KEY = get_secret_setting(
    "INTERPRETATION_HMAC_KEY",
    "INTERPRETATION_HMAC_KEY_FILE",
)
# Groq currently documents strict JSON Schema decoding only for these GPT-OSS
# models. Production is fail-closed so changing the model cannot silently
# weaken the response contract to JSON Object Mode.
GROQ_ALLOWED_MODELS = (
    "openai/gpt-oss-120b",
    "openai/gpt-oss-20b",
)
GROQ_MODEL = (
    str(aplication_config.get("GROQ_MODEL", "") or "").strip()
    or "openai/gpt-oss-120b"
)

if GROQ_MODEL not in GROQ_ALLOWED_MODELS:
    raise ImproperlyConfigured(
        "GROQ_MODEL debe ser uno de estos valores: "
        + ", ".join(GROQ_ALLOWED_MODELS)
    )

# Provider secrets remain optional for migrations and offline commands. The
# application container enables this switch to fail before serving requests.
LLM_PROVIDER_REQUIRED = get_boolean_setting(
    "LLM_PROVIDER_REQUIRED",
    default=False,
)

if LLM_PROVIDER_REQUIRED and not GROQ_API_KEY:
    raise ImproperlyConfigured(
        "Debe configurarse GROQ_API_KEY o GROQ_API_KEY_FILE."
    )

if LLM_PROVIDER_REQUIRED and not INTERPRETATION_HMAC_KEY:
    raise ImproperlyConfigured(
        "Debe configurarse INTERPRETATION_HMAC_KEY o "
        "INTERPRETATION_HMAC_KEY_FILE."
    )

if (
    INTERPRETATION_HMAC_KEY
    and len(INTERPRETATION_HMAC_KEY.encode("utf-8")) < 32
):
    raise ImproperlyConfigured(
        "INTERPRETATION_HMAC_KEY debe contener al menos 32 bytes UTF-8."
    )

# These limits are server-owned and cannot be overridden by API clients.
# Keep the combined target-and-context limit as a fixed product contract shared
# with React; deployment overrides would make the browser and Django disagree.
LLM_MAX_INPUT_CHARACTERS = 500
LLM_MAX_COMPLETION_TOKENS = get_integer_setting(
    "LLM_MAX_COMPLETION_TOKENS",
    default=1200,
    minimum=128,
    maximum=2000,
)
LLM_MAX_VISUAL_CONCEPTS = get_integer_setting(
    "LLM_MAX_VISUAL_CONCEPTS",
    default=5,
    minimum=0,
    maximum=10,
)
LLM_MAX_VISUAL_CONCEPT_CHARACTERS = get_integer_setting(
    "LLM_MAX_VISUAL_CONCEPT_CHARACTERS",
    default=40,
    minimum=8,
    maximum=64,
)
# ARASAAC has no backend credential. Its HTTPS origins remain fixed in code so
# environment configuration cannot turn Django into a proxy to another host.
ARASAAC_CONNECT_TIMEOUT_SECONDS = get_integer_setting(
    "ARASAAC_CONNECT_TIMEOUT_SECONDS",
    default=2,
    minimum=1,
    maximum=5,
)
ARASAAC_READ_TIMEOUT_SECONDS = get_integer_setting(
    "ARASAAC_READ_TIMEOUT_SECONDS",
    default=3,
    minimum=1,
    maximum=10,
)
ARASAAC_TOTAL_TIMEOUT_SECONDS = get_integer_setting(
    "ARASAAC_TOTAL_TIMEOUT_SECONDS",
    default=5,
    minimum=1,
    maximum=15,
)
# Cache matches for one day and retry catalogue misses after fifteen minutes.
ARASAAC_CACHE_ALIAS = "arasaac"
ARASAAC_CACHE_TTL_SECONDS = get_integer_setting(
    "ARASAAC_CACHE_TTL_SECONDS",
    default=86_400,
    minimum=0,
    maximum=604_800,
)
ARASAAC_NOT_FOUND_CACHE_TTL_SECONDS = get_integer_setting(
    "ARASAAC_NOT_FOUND_CACHE_TTL_SECONDS",
    default=900,
    minimum=0,
    maximum=3_600,
)

if ARASAAC_TOTAL_TIMEOUT_SECONDS < ARASAAC_CONNECT_TIMEOUT_SECONDS:
    raise ImproperlyConfigured(
        "ARASAAC_TOTAL_TIMEOUT_SECONDS no debe ser inferior a "
        "ARASAAC_CONNECT_TIMEOUT_SECONDS."
    )
LLM_CONNECT_TIMEOUT_SECONDS = get_integer_setting(
    "LLM_CONNECT_TIMEOUT_SECONDS",
    default=3,
    minimum=1,
    maximum=10,
)
LLM_READ_TIMEOUT_SECONDS = get_integer_setting(
    "LLM_READ_TIMEOUT_SECONDS",
    default=20,
    minimum=3,
    maximum=60,
)
LLM_MAX_ATTEMPTS = get_integer_setting(
    "LLM_MAX_ATTEMPTS",
    default=2,
    minimum=1,
    maximum=3,
)
LLM_RETRY_BASE_MILLISECONDS = get_integer_setting(
    "LLM_RETRY_BASE_MILLISECONDS",
    default=250,
    minimum=100,
    maximum=2000,
)
LLM_MAX_RETRY_DELAY_SECONDS = get_integer_setting(
    "LLM_MAX_RETRY_DELAY_SECONDS",
    default=2,
    minimum=1,
    maximum=10,
)
LLM_TOTAL_TIMEOUT_SECONDS = get_integer_setting(
    "LLM_TOTAL_TIMEOUT_SECONDS",
    default=30,
    minimum=5,
    maximum=120,
)
LLM_MAX_CONCURRENT_PROVIDER_CALLS_PER_PROCESS = get_integer_setting(
    "LLM_MAX_CONCURRENT_PROVIDER_CALLS_PER_PROCESS",
    default=4,
    minimum=1,
    maximum=16,
)
# Select the backend that stores only short-lived, content-free HMAC markers.
# Namespaced keys separate duplicate suppression, early attempt throttling, and
# audit deduplication without introducing independent cache dependencies.
LLM_DUPLICATE_CACHE_ALIAS = (
    str(
        aplication_config.get("LLM_DUPLICATE_CACHE_ALIAS", "default")
        or "default"
    )
    .strip()
    or "default"
)
# A production deployment must coordinate duplicate markers across all workers.
LLM_REQUIRE_SHARED_DUPLICATE_CACHE = get_boolean_setting(
    "LLM_REQUIRE_SHARED_DUPLICATE_CACHE",
    default=not DEBUG,
)
# Post-success period during which an identical request remains suppressed. The
# initial in-flight lease additionally includes LLM_TOTAL_TIMEOUT_SECONDS.
LLM_DUPLICATE_TTL_SECONDS = get_integer_setting(
    "LLM_DUPLICATE_TTL_SECONDS",
    default=15,
    minimum=1,
    maximum=60,
)
# These cache-backed limits count every authenticated endpoint attempt before
# JSON parsing. They supplement, but do not replace, transactional LLM quotas.
LLM_INTERPRETATION_ATTEMPTS_PER_MINUTE = get_integer_setting(
    "LLM_INTERPRETATION_ATTEMPTS_PER_MINUTE",
    default=10,
    minimum=1,
    maximum=300,
)
LLM_INTERPRETATION_ATTEMPTS_PER_DAY = get_integer_setting(
    "LLM_INTERPRETATION_ATTEMPTS_PER_DAY",
    default=100,
    minimum=1,
    maximum=10_000,
)
# Pseudonymous quota rows outlive the longest one-day window only briefly.
# A manual management command applies this policy until production scheduling
# is introduced.
LLM_RATE_LIMIT_STATE_RETENTION_DAYS = get_integer_setting(
    "LLM_RATE_LIMIT_STATE_RETENTION_DAYS",
    default=2,
    minimum=2,
    maximum=7,
)

if (
    LLM_RETRY_BASE_MILLISECONDS
    > LLM_MAX_RETRY_DELAY_SECONDS * 1000
):
    raise ImproperlyConfigured(
        "LLM_RETRY_BASE_MILLISECONDS no debe superar "
        "LLM_MAX_RETRY_DELAY_SECONDS."
    )

if LLM_TOTAL_TIMEOUT_SECONDS < LLM_CONNECT_TIMEOUT_SECONDS:
    raise ImproperlyConfigured(
        "LLM_TOTAL_TIMEOUT_SECONDS no debe ser inferior a "
        "LLM_CONNECT_TIMEOUT_SECONDS."
    )

# Application-owned quotas must be reviewed against the exact organization
# limits shown in Groq Console, which can differ from public plan summaries.
LLM_USER_REQUESTS_PER_MINUTE = get_integer_setting(
    "LLM_USER_REQUESTS_PER_MINUTE",
    default=3,
    minimum=1,
    maximum=30,
)
LLM_USER_REQUESTS_PER_DAY = get_integer_setting(
    "LLM_USER_REQUESTS_PER_DAY",
    default=30,
    minimum=1,
    maximum=1000,
)
LLM_USER_TOKENS_PER_MINUTE = get_integer_setting(
    "LLM_USER_TOKENS_PER_MINUTE",
    default=7000,
    minimum=1000,
    maximum=8000,
)
LLM_USER_TOKENS_PER_DAY = get_integer_setting(
    "LLM_USER_TOKENS_PER_DAY",
    default=50000,
    minimum=1000,
    maximum=125000,
)
LLM_GLOBAL_REQUESTS_PER_MINUTE = get_integer_setting(
    "LLM_GLOBAL_REQUESTS_PER_MINUTE",
    default=10,
    minimum=1,
    maximum=30,
)
LLM_GLOBAL_REQUESTS_PER_DAY = get_integer_setting(
    "LLM_GLOBAL_REQUESTS_PER_DAY",
    default=200,
    minimum=1,
    maximum=1000,
)
LLM_GLOBAL_TOKENS_PER_MINUTE = get_integer_setting(
    "LLM_GLOBAL_TOKENS_PER_MINUTE",
    default=7000,
    minimum=1000,
    maximum=8000,
)
LLM_GLOBAL_TOKENS_PER_DAY = get_integer_setting(
    "LLM_GLOBAL_TOKENS_PER_DAY",
    default=90000,
    minimum=1000,
    maximum=200000,
)

if (
    LLM_USER_REQUESTS_PER_MINUTE > LLM_GLOBAL_REQUESTS_PER_MINUTE
    or LLM_USER_REQUESTS_PER_DAY > LLM_GLOBAL_REQUESTS_PER_DAY
    or LLM_USER_TOKENS_PER_MINUTE > LLM_GLOBAL_TOKENS_PER_MINUTE
    or LLM_USER_TOKENS_PER_DAY > LLM_GLOBAL_TOKENS_PER_DAY
):
    raise ImproperlyConfigured(
        "Las cuotas de LLM por usuario no deben superar las cuotas globales "
        "correspondientes."
    )

if (
    LLM_INTERPRETATION_ATTEMPTS_PER_MINUTE
    < LLM_USER_REQUESTS_PER_MINUTE
    or LLM_INTERPRETATION_ATTEMPTS_PER_DAY < LLM_USER_REQUESTS_PER_DAY
):
    raise ImproperlyConfigured(
        "Los límites de intentos de interpretación no deben ser inferiores "
        "a las cuotas de solicitudes LLM por usuario correspondientes."
    )

if any(
    LLM_MAX_COMPLETION_TOKENS > token_limit
    for token_limit in (
        LLM_USER_TOKENS_PER_MINUTE,
        LLM_USER_TOKENS_PER_DAY,
        LLM_GLOBAL_TOKENS_PER_MINUTE,
        LLM_GLOBAL_TOKENS_PER_DAY,
    )
):
    raise ImproperlyConfigured(
        "LLM_MAX_COMPLETION_TOKENS no debe superar ninguna cuota de tokens. "
        "La comprobación completa del prompt se realiza en cada solicitud."
    )
